resolver: lts-14.22

packages:
- .
- ./ghcide/

extra-deps:
- ansi-terminal-0.10.2
- base-compat-0.11.0
# - cabal-helper-1.0.0.0
- github: DanielG/cabal-helper
  commit: a18bbb2af92e9b4337e7f930cb80754f2408bcfd
- cabal-plan-0.6.2.0
- clock-0.7.2
- floskell-0.10.2
- fuzzy-0.1.0.0
# - ghcide-0.1.0
- ghc-check-0.1.0.3
- ghc-lib-parser-8.8.2
- haddock-library-1.8.0
- haskell-lsp-0.21.0.0
- haskell-lsp-types-0.21.0.0
# - hie-bios-0.4.0
- github: fendor/hie-bios
  commit: d5b7fc9bb3025b1d4d2ac9c48b588faf18dfce99
- indexed-profunctors-0.1
- lsp-test-0.10.2.0
- monad-dijkstra-0.1.1.2
- optics-core-0.2
- optparse-applicative-0.15.1.0
- ormolu-0.0.3.1
- parser-combinators-1.2.1
- regex-base-0.94.0.0
- regex-pcre-builtin-0.95.1.1.8.43
- regex-tdfa-1.3.1.0
- semialign-1.1
- tasty-rerun-1.1.17
- temporary-1.2.1.1
- topograph-1

flags:
  haskell-language-server:
    pedantic: true

# allow-newer: true

nix:
  packages: [ icu libcxx zlib ]

concurrent-tests: false
