name: "HLint check"

on:
  pull_request:
    branches:
      - '**'

jobs:
  hlint:
    name: "Hlint check run"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: 'Installing'
      uses: rwe/actions-hlint-setup@v1
      with:
        version: '3.5'

    - name: 'Checking code'
      uses: rwe/actions-hlint-run@v2
      with:
        # Ignore testdata directories to silence hlint warnings for test data files.
        hlint-bin: "hlint --with-group=extra --ignore-glob='**/testdata/**/*.hs' --ignore-glob='**/test/data/**/*.hs'"
        fail-on: error
        path: .

